name: Publish Artifacts

on:
  release:
    types:
      - published

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: build/libs/*-all.jar
          github-files: build/libs/*-all.jar
          version-type: release
          game-versions: 1.20.1
          game-version-filter: releases
          dependencies: |
            better_mods_button(incompatible){modrinth:KUZAAwdD}{curseforge:541584}#(ignore:github)
          modrinth-featured: true
          modrinth-id: sbpqhzIG
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1089803
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: |
            neoforge
            forge
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip